import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "mahdi-hashemi-web",
  description: "Generated by create Mahdi",
};

export default function RootLayout({ children }) {
  console.log(children);


  return (
    <html  lang="en" className="font-mhd1 *:font-mhd1 bg-maghzPeste">
      <body className={inter.className}>
        
        
        {children}
       
       <footer className="flex justify-center overflow-hidden  flex-wrap lg:translate-y-[-100px]">
       <Footer  />
       </footer>
      </body>
    </html>
  );
}




